# Generated by Django 4.2.6 on 2023-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='auth'),
        ),
    ]
