# Generated by Django 4.2.6 on 2023-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0002_user_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
    ]
