# Generated by Django 4.2.6 on 2023-12-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0003_alter_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='popup',
            new_name='text',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='null', max_length=13),
            preserve_default=False,
        ),
    ]
