# Generated by Django 4.2.6 on 2023-12-23 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0004_alter_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Event_Qty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('dinner', models.IntegerField(default=0)),
                ('bar', models.IntegerField(default=0)),
                ('leisure', models.IntegerField(default=0)),
                ('relaxation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_qty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
