# Generated by Django 4.2.6 on 2023-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0004_rename_popup_event_text_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('DINNERS', 'Dinners'), ('BAR', 'Bar'), ('LEISURE', 'Leisure'), ('RELAX', 'Relax')], default='HEALTH', max_length=20),
            preserve_default=False,
        ),
    ]
