# Generated by Django 4.2.6 on 2023-12-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0005_user_event_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='bar',
            new_name='BAR',
        ),
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='dinner',
            new_name='DINNER',
        ),
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='education',
            new_name='EDUCATION',
        ),
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='health',
            new_name='HEALTH',
        ),
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='leisure',
            new_name='LEISURE',
        ),
        migrations.RenameField(
            model_name='user_event_qty',
            old_name='relaxation',
            new_name='RELAXATION',
        ),
    ]
