# Generated by Django 4.2.6 on 2023-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0005_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTE', 'Accepted'), ('REJECTED', 'Rejected')], default='pending', max_length=20),
        ),
    ]
