# Generated by Django 4.2.6 on 2023-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0006_alter_friendship_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='id',
        ),
        migrations.AddField(
            model_name='friendship',
            name='request_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
