# Generated by Django 4.2.6 on 2023-12-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0007_alter_user_event_qty_health'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Event_Qty',
        ),
    ]
