# Generated by Django 4.2.6 on 2023-11-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0007_remove_friendship_id_friendship_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='request_id',
            new_name='friendship_id',
        ),
    ]
