# Generated by Django 4.2.6 on 2023-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0009_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('DINNER', 'Dinner'), ('BAR', 'Bar'), ('LEISURE', 'Leisure'), ('RELAXATION', 'Relaxation'), ('HOLIDAY', 'Holiday'), ('WORK', 'Work'), ('TRAVEL', 'Travel'), ('SHOPING', 'Shoping')], max_length=20),
        ),
    ]
