# Generated by Django 4.2.6 on 2023-12-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0009_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
