# Generated by Django 4.2.6 on 2023-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0010_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
