# Generated by Django 4.2.6 on 2023-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0011_remove_event_id_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marker_id',
            field=models.FloatField(default=121233),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='popup',
            field=models.CharField(default=123213, max_length=256),
            preserve_default=False,
        ),
    ]
