# Generated by Django 4.2.6 on 2023-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0013_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
