# Generated by Django 4.2.6 on 2023-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(default='<i class="fa-solid fa-sack-xmark"></i>', max_length=64),
            preserve_default=False,
        ),
    ]
