# Generated by Django 4.2.6 on 2023-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0016_event_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(max_length=128),
        ),
    ]
