# Generated by Django 4.2.6 on 2024-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0019_alter_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='value',
            field=models.CharField(default='A', max_length=32),
            preserve_default=False,
        ),
    ]
