# Generated by Django 4.2.6 on 2024-01-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0021_alter_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='value',
        ),
    ]
