# Generated by Django 4.2.6 on 2024-01-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0022_remove_interest_icon_remove_interest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateField(),
        ),
    ]
