# Generated by Django 4.2.6 on 2024-01-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0025_event_date_alter_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='time',
            new_name='date',
        ),
    ]
