# Generated by Django 4.2.6 on 2024-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0028_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
