# Generated by Django 4.2.6 on 2024-01-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0029_rename_time_event__time_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='date',
            new_name='event_date',
        ),
    ]
