# Generated by Django 4.2.6 on 2024-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0030_rename_date_mail_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
