# Generated by Django 4.2.6 on 2024-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0031_alter_mail_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='event_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
