# Generated by Django 4.2.6 on 2024-01-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0033_blocklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blocklist',
        ),
    ]
