# Generated by Django 4.2.6 on 2024-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0035_event_archived_alter_event_recipient_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_recipient',
            old_name='is_accepted',
            new_name='status',
        ),
    ]
