# Generated by Django 4.2.6 on 2024-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0038_alter_event_recipient_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='initial_recipients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
