# Generated by Django 4.2.6 on 2024-01-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0039_event_initial_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initial_recipients',
            field=models.JSONField(default=list),
        ),
    ]
