# Generated by Django 4.2.6 on 2024-01-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0041_alter_event_requester_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
