# Generated by Django 4.2.6 on 2024-01-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0042_alter_event_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archived',
        ),
    ]
