# Generated by Django 4.2.6 on 2024-01-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0043_remove_event_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArchived',
            fields=[
                ('category', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('_time', models.TimeField()),
                ('sent', models.DateField(auto_now_add=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=128)),
                ('initial_recipients', models.JSONField(default=list)),
                ('recipients', models.ManyToManyField(related_name='arhcived_recivied_events', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_sent_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
