# Generated by Django 4.2.6 on 2024-01-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0044_eventarchived'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventArchived',
            new_name='Event_Archived',
        ),
    ]
