# Generated by Django 4.2.6 on 2024-01-12 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0045_rename_eventarchived_event_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_archived',
            name='recipients',
            field=models.ManyToManyField(related_name='archived_recivied_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
