# Generated by Django 4.2.6 on 2024-01-12 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0046_alter_event_archived_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_archived',
            name='recipients',
            field=models.ManyToManyField(related_name='archived_recievied_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
