# Generated by Django 4.2.6 on 2024-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0047_alter_event_archived_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_archived',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_archived',
            name='is_depricated',
            field=models.BooleanField(default=False),
        ),
    ]
