# Generated by Django 4.2.6 on 2024-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0049_alter_event_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='initial_requester',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event_archived',
            name='initial_requester',
            field=models.JSONField(default=dict),
        ),
    ]
