# Generated by Django 4.2.6 on 2024-01-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0050_event_initial_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_archived',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='event_archived',
            name='requester',
        ),
        migrations.AddField(
            model_name='event_archived',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
