# Generated by Django 4.2.6 on 2024-01-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0051_remove_event_archived_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_archived',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
