# Generated by Django 4.2.6 on 2024-01-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0052_alter_event_archived_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_archived',
            old_name='is_depricated',
            new_name='is_deprecated',
        ),
    ]
