# Generated by Django 4.2.6 on 2024-01-13 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0053_rename_is_depricated_event_archived_is_deprecated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_archived',
            name='user',
        ),
        migrations.AddField(
            model_name='event_archived',
            name='users',
            field=models.ManyToManyField(related_name='archived_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
