# Generated by Django 4.2.6 on 2024-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planpro', '0055_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
